Resources:
  Assets:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Assets
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S 
      KeySchema:
        - AttributeName: id
          KeyType: HASH