service:
  name: advl-api

frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  cors:
    v1: true
    prod: false

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: v1
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds-data:ExecuteStatement"
        - "secretsmanager:*"
        - "ec2:*"
      Resource:
        - "*"
  environment:
    ${file(src/.env.yml):common}
    
functions:
  - ${file(src/api/api.yml)}
  # - ${file(src/workers/workers.yml)}

resources:
  # - ${file(src/resources/dynamodb.yml)}