service:
  name: advl-api

frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: v1
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds-data:ExecuteStatement"
        - "secretsmanager:*"
      Resource:
        - "arn:aws:rds:us-east-1:575357632480:cluster:advl-test-db-2"
        - "arn:aws:secretsmanager:us-east-1:575357632480:secret:rds-db-credentials/cluster-CSIWAG2LX6VEWLR23DWNHFJ5VU/advl-EA98Jl"
  environment:
    ${file(src/.env.yml):common}
    
functions:
  - ${file(src/api/api.yml)}
  # - ${file(src/workers/workers.yml)}

resources:
  # - ${file(src/resources/dynamodb.yml)}