service:
  name: advl-api

frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - v1
    start:
      port: 8000
      dbPath: database
      migrate: true
      seed: true
    seed: 
      assets:
        sources:
          - table: Assets
            sources: ["./database/seed/assets.json"]
      tags:
        sources:
          - table: Categorization
            sources: ['./database/seed/categorization.json']

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  stage: v1
  runtime: nodejs12.x
  memorySize: 128
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    ${file(src/.env.yml):common}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  - ${file(src/api/api.yml)}
  # - ${file(src/workers/workers.yml)}

resources:
  - ${file(src/resources/dynamodb.yml)}