BEGIN;
DROP TABLE IF EXISTS vin_bundle_assets;
DROP TABLE IF EXISTS vin_bundles;
DROP TABLE IF EXISTS vin_creator_access;
DROP TABLE IF EXISTS vin_assets;
DROP TABLE IF EXISTS vin_creators;
DROP TABLE IF EXISTS vin_users;
DROP TYPE IF EXISTS vin_visibility;
DROP TYPE IF EXISTS vin_filetype;
DROP TYPE IF EXISTS vin_asset_type;
COMMIT;
